// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHVle3O8Hr3Ai4Md0fU_HaxolxTRqEpKQ',
    appId: '1:726674799836:web:ed36812623262eaf5f0819',
    messagingSenderId: '726674799836',
    projectId: 'newauth-7a00a',
    authDomain: 'newauth-7a00a.firebaseapp.com',
    storageBucket: 'newauth-7a00a.appspot.com',
    measurementId: 'G-2JF5XML6WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEF9f_YXplFlJ0Kd_YzSchBeTekwG-TuA',
    appId: '1:726674799836:android:9e24f1acb2c0f2d85f0819',
    messagingSenderId: '726674799836',
    projectId: 'newauth-7a00a',
    storageBucket: 'newauth-7a00a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9w2X9DW5h1d1T3YcEbvSyVECkHvrpzxg',
    appId: '1:726674799836:ios:ab6d240fa3cc1e085f0819',
    messagingSenderId: '726674799836',
    projectId: 'newauth-7a00a',
    storageBucket: 'newauth-7a00a.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9w2X9DW5h1d1T3YcEbvSyVECkHvrpzxg',
    appId: '1:726674799836:ios:a943f0638dba2f455f0819',
    messagingSenderId: '726674799836',
    projectId: 'newauth-7a00a',
    storageBucket: 'newauth-7a00a.appspot.com',
    iosBundleId: 'com.example.firebaseTutorial.RunnerTests',
  );
}
